/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rentalbarang;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
/**
 *
 * @author ASUS TUF
 */
public class addItemPannel extends javax.swing.JPanel {
    

    /**
     * Creates new form cartPannel
     */
        public addItemPannel() {
        initComponents();
        loadCategory();
    }
        
    private void loadCategory() {

    try {

        Connection conn =
                DatabaseConnection.connect();

        String sql =
                "SELECT category_name FROM category";

        PreparedStatement pstmt =
                conn.prepareStatement(sql);

        ResultSet rs =
                pstmt.executeQuery();

        cmbCategory.removeAllItems();

        while (rs.next()) {

            cmbCategory.addItem(
                    rs.getString("category_name")
            );

        }

        rs.close();
        pstmt.close();
        conn.close();

    } catch (SQLException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );

    }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextItemName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextDesc = new javax.swing.JTextArea();
        jTextFullPrice = new javax.swing.JTextField();
        jButtonSumitItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("UPLOAD IMAGE");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextItemName.addActionListener(this::jTextItemNameActionPerformed);

        jTextDesc.setColumns(20);
        jTextDesc.setRows(5);
        jScrollPane2.setViewportView(jTextDesc);

        jTextFullPrice.addActionListener(this::jTextFullPriceActionPerformed);

        jButtonSumitItem.setText("Submit item");
        jButtonSumitItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSumitItemMouseClicked(evt);
            }
        });
        jButtonSumitItem.addActionListener(this::jButtonSumitItemActionPerformed);

        jLabel2.setText("Input item name");

        jLabel3.setText("Input in description");

        jLabel4.setText("Input price");

        jLabel6.setText("Select Category");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategory.addActionListener(this::cmbCategoryActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSumitItem, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jTextItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(jTextFullPrice)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFullPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSumitItem)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextItemNameActionPerformed
            if(jTextItemName.getText().trim().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Nama barang tidak boleh kosong!"
            );
        }
    }//GEN-LAST:event_jTextItemNameActionPerformed

    private void jTextFullPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFullPriceActionPerformed
         try{
            Double.parseDouble(
                    jTextFullPrice.getText().trim()
            );

        }catch(NumberFormatException e){

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Harga harus berupa angka!"
            );

            jTextFullPrice.requestFocus();

        }
    }//GEN-LAST:event_jTextFullPriceActionPerformed

    private void jButtonSumitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumitItemActionPerformed
            String kategori =
            (String)cmbCategory.getSelectedItem();

            System.out.println(
                    "Kategori dipilih : " + kategori
            );

    }//GEN-LAST:event_jButtonSumitItemActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
    
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void jButtonSumitItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSumitItemMouseClicked
                                                        
    String itemName = jTextItemName.getText().trim();
    String itemDesc = jTextDesc.getText().trim();
    String itemPrice = jTextFullPrice.getText().trim();
    String categoryName = (String) cmbCategory.getSelectedItem();
    String condition = 

    if (itemName.isEmpty() || itemDesc.isEmpty() || itemPrice.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
        return;
    }

    try {
        double price = Double.parseDouble(itemPrice);


        Connection conn = DatabaseConnection.connect();

        // 1. LOOK UP THE CATEGORY_ID BASED ON THE NAME SELECTED
        String getCatIdSql = "SELECT category_id FROM category WHERE category_name = ?";
        PreparedStatement catPstmt = conn.prepareStatement(getCatIdSql);
        catPstmt.setString(1, categoryName);
        ResultSet catRs = catPstmt.executeQuery();
        
        int categoryId = 0;
        if (catRs.next()) {
            categoryId = catRs.getInt("category_id");
        }
        catRs.close();
        catPstmt.close();

        // If for some reason we couldn't map the category id, halt.
        if (categoryId == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kategori tidak valid!");
            return;
        }

        // 2. INSERT INTO THE ITEM TABLE MATCHING YOUR EXACT SCHEMA
        String sql = "INSERT INTO item "
                + "(user_id, category_id, item_name, item_desc, "
                + "item_price_per_day, item_condition, "
                + "item_status, item_image) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)"; // 9 parameters

        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, UserSession.getUserId());
        pstmt.setInt(2, categoryId); // Matches your int category_id column!
        pstmt.setString(3, itemName);
        pstmt.setString(4, itemDesc);
        pstmt.setDouble(5, price);
        pstmt.setString(6, "Baik");
        pstmt.setString(7, "Available"); // Matches your enum('Available', 'Rented') precisely!
        pstmt.setString(8, ""); // item_image empty string

        pstmt.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "Item berhasil ditambahkan!");
        DashboardPannel defaultPannel = new DashboardPannel();
        
        // Clear out text fields
        jTextItemName.setText("");
        jTextDesc.setText("");
        jTextFullPrice.setText("");
        
        
        pstmt.close();
        conn.close();

    } catch (NumberFormatException nfe) {
        javax.swing.JOptionPane.showMessageDialog(this, "Harga dan Deposit harus berupa angka!");
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error Database: " + e.getMessage());
    }

    }//GEN-LAST:event_jButtonSumitItemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JButton jButtonSumitItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextDesc;
    private javax.swing.JTextField jTextFullPrice;
    private javax.swing.JTextField jTextItemName;
    // End of variables declaration//GEN-END:variables
}
