/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rentalbarang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author ASUS TUF
 */
public class DashboardPannel extends javax.swing.JPanel {

    /**
     * Creates new form dashboardPannel
     */
    public DashboardPannel() {
        initComponents();
        displayItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemDisplayLabel = new javax.swing.JLabel();
        cardHolderPannel = new javax.swing.JPanel();

        itemDisplayLabel.setText("Reccomended item");

        cardHolderPannel.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(itemDisplayLabel)
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardHolderPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(itemDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardHolderPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void displayItems() {
    cardHolderPannel.removeAll(); 
    cardHolderPannel.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
    
    // 1. Update your SQL query to fetch ALL the columns you want to display
    String sql = "SELECT item_name, item_price_per_day, item_status, item_condition, item_desc FROM item";
    
    try (java.sql.Connection conn = DatabaseConnection.connect();
         java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
         java.sql.ResultSet rs = pstmt.executeQuery()) {
         
        while(rs.next()) {
            String name = rs.getString("item_name");
            double price = rs.getDouble("item_price_per_day");
            String status = rs.getString("item_status");
            String condition = rs.getString("item_condition");
            String description = rs.getString("item_desc"); // Matches 'item_desc' from your table
            
            // Your dashboard card preview can stay simple with just name and price
            DashboardItemCard card = new DashboardItemCard(name, price);
            
            // 2. Attach the click listener using your upgraded constructor!
            card.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    // ✅ Pass all 5 arguments in the exact order your constructor demands them!
                    itemDetailForm detailForm = new itemDetailForm(name, price, status, condition, description);
                    detailForm.setVisible(true);
                }
            });
            
            cardHolderPannel.add(card);
        }
        
        cardHolderPannel.revalidate();
        cardHolderPannel.repaint();
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat barang: " + e.getMessage());
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardHolderPannel;
    private javax.swing.JLabel itemDisplayLabel;
    // End of variables declaration//GEN-END:variables
}
