/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalbarang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author ASUS TUF
 */
public class editDataForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editDataForm.class.getName());

    // 1. ADD THIS FIELD VARIABLE HERE SO THE CLASS KNOWS WHAT parentFrame IS:
    private MainForm MainForm;

    // 2. THIS IS THE CONSTRUCTOR METHOD YOU ARE REPLACING:
    public editDataForm(MainForm parent) {
        this.MainForm = parent;
        initComponents();
        
        // This overrides NetBeans and prevents the app from closing entirely!
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        defData();
    }

    // Leave this empty one here too so NetBeans doesn't complain
    public editDataForm() {
        initComponents();
        defData();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phoneEdit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adressEdit = new javax.swing.JTextField();
        editUserData = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Edit User Data");

        nameEdit.setText("jTextField1");

        jLabel2.setText("Name:");

        jLabel3.setText("Email:");

        emailEdit.setText("jTextField2");
        emailEdit.addActionListener(this::emailEditActionPerformed);

        jLabel4.setText("Password:");

        passEdit.setText("jTextField3");

        jLabel5.setText("Phone:");

        phoneEdit.setText("jTextField4");

        jLabel6.setText("Adress:");

        adressEdit.setText("jTextField5");

        editUserData.setText("Edit Data");
        editUserData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editUserDataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameEdit)
                            .addComponent(emailEdit)
                            .addComponent(passEdit)
                            .addComponent(phoneEdit)
                            .addComponent(adressEdit)
                            .addComponent(editUserData, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(editUserData)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void defData(){
        nameEdit.setText(UserSession.getUsername());
        emailEdit.setText(UserSession.getEmail());
        passEdit.setText(UserSession.getPass());
        phoneEdit.setText(UserSession.getPhone());
        adressEdit.setText(UserSession.getAdress());
    }
    private void emailEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailEditActionPerformed

    private void editUserDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUserDataMouseClicked
                                                
    // 1. Extract strings from fields
    String newUsername = nameEdit.getText().trim();
    String newEmail    = emailEdit.getText().trim();
    String newPassword = passEdit.getText().trim();
    String newPhone    = phoneEdit.getText().trim();
    String newAddress  = adressEdit.getText().trim();

    if (newUsername.isEmpty() || newEmail.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Username and Email cannot be empty.");
        return;
    }

    Connection conn = DatabaseConnection.connect();
    String sql = "UPDATE users SET user_name = ?, user_email = ?, user_password = ?, user_phone = ?, user_adress = ? WHERE user_id = ?";

    try {
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, newUsername);
        pstmt.setString(2, newEmail);
        pstmt.setString(3, newPassword);
        pstmt.setString(4, newPhone);
        pstmt.setString(5, newAddress);
        pstmt.setInt(6, UserSession.getUserId());

        int rowsUpdated = pstmt.executeUpdate();

        if (rowsUpdated > 0) {
            // Mirror data to session RAM fields
            UserSession.startSession(
                UserSession.getUserId(),
                newUsername, 
                newEmail, 
                newPassword, 
                newPhone, 
                newAddress
            );

            javax.swing.JOptionPane.showMessageDialog(this, "Profile data updated successfully!");
            // ✅ TO THIS LINE:
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            // 🚀 THE FIX: Tell the older parent frame to re-read the session and update its labels!
            if (MainForm != null) {
                MainForm.refreshProfileUI(); 
            }
            
            // Close this edit form window framework cleanly
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to update profile.");
        }

        pstmt.close();
        conn.close();
    } catch (SQLException e) {
        System.out.println("Database Update Error: " + e.getMessage());
    }

    }//GEN-LAST:event_editUserDataMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
                                        
    // 1. Extract the newly edited text strings out of your UI fields
    String newUsername = nameEdit.getText().trim();
    String newEmail    = emailEdit.getText().trim();
    String newPassword = String.valueOf(passEdit.getText());
    String newPhone    = phoneEdit.getText().trim();
    String newAddress  = adressEdit.getText().trim();

    // Validation: Ensure crucial identity fields aren't accidentally left blank
    if (newUsername.isEmpty() || newEmail.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Username and Email cannot be empty.");
        return;
    }

    // 2. Establish the connection pipeline to MySQL
    Connection conn = DatabaseConnection.connect();
    
    // SQL Logic: Target ONLY the row matching our current logged-in session ID
    String sql = "UPDATE users SET user_name = ?, user_email = ?, user_password = ?, user_phone = ?, user_adress = ? WHERE user_id = ?";

    try {
        PreparedStatement pstmt = conn.prepareStatement(sql);
        
        // Inject the freshly edited values into the SQL query layout map
        pstmt.setString(1, newUsername);
        pstmt.setString(2, newEmail);
        pstmt.setString(3, newPassword);
        pstmt.setString(4, newPhone);
        pstmt.setString(5, newAddress);
        
        // 🔒 CRUCIAL: Secure the WHERE clause using the active Session ID footprint
        pstmt.setInt(6, UserSession.getUserId());

        // Execute the statement update command against the database engine
        int rowsUpdated = pstmt.executeUpdate();

        if (rowsUpdated > 0) {
            // 🚀 STEP 3: DATABASE SUCCESSFUL -> MIRROR THE CHANGES TO YOUR RAM SESSION
            UserSession.startSession(
                UserSession.getUserId(), // ID stays the same
                newUsername,             // Overwrite with new name
                newEmail,                // Overwrite with new email
                newPassword,             // Overwrite with new password
                newPhone,                // Overwrite with new phone
                newAddress               // Overwrite with new address
            );

            // Notify the user that everything processed perfectly
            javax.swing.JOptionPane.showMessageDialog(this, "Profile data updated successfully!");
            this.dispose();
            // Optional: Close this edit frame panel or switch views back to Dashboard here
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to update profile. User row not found.");
        }

        // Close your database communication lines neatly
        pstmt.close();
        conn.close();

    } catch (SQLException e) {
        System.out.println("Database Update Error: " + e.getMessage());
        javax.swing.JOptionPane.showMessageDialog(this, "SQL Error: " + e.getMessage());
    }

    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new editDataForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adressEdit;
    private javax.swing.JButton editUserData;
    private javax.swing.JTextField emailEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameEdit;
    private javax.swing.JTextField passEdit;
    private javax.swing.JTextField phoneEdit;
    // End of variables declaration//GEN-END:variables
}
