/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rentalbarang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author ASUS TUF
 */
public class LoginPannel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPannel
     */
    public LoginPannel() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailInput = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        passInput = new javax.swing.JPasswordField();

        emailInput.addActionListener(this::emailInputActionPerformed);

        emailLabel.setText("Email");

        passLabel.setText("Password");

        logInButton.setText("Login");
        logInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logInButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passLabel)
                            .addComponent(emailLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(passInput))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(logInButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void logInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInButtonMouseClicked

    String inputEmail = emailInput.getText().trim();
    String inputPass = String.valueOf(passInput.getPassword());

    Connection conn = DatabaseConnection.connect();
    // We select the unique 'id' and 'email' along with verification
    String sql = "SELECT user_id, user_name, user_email, user_adress,user_phone, user_password FROM users WHERE user_email = ? AND user_password = ?";

    try {
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, inputEmail);
        pstmt.setString(2, inputPass);

        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // SYNTAX BREAKDOWN: Extract data out of the database row columns
            int idFromDB = rs.getInt("user_id");
            String userFromDB = rs.getString("user_name");
            String emailFromDB = rs.getString("user_email");
            String passFromDB = rs.getString("user_password");
            String phoneFromDB = rs.getString("user_phone");      
            String addressFromDB = rs.getString("user_adress");

            // ACTIVATING THE SESSION: Pass the extracted data into our RAM card
            UserSession.startSession(idFromDB, userFromDB,emailFromDB, passFromDB, phoneFromDB, addressFromDB);

            javax.swing.JOptionPane.showMessageDialog(this, "Welcome back, " + UserSession.getUsername() + "!");
            
            // Switch to Dashboard frame
            MainForm nextScreen = new MainForm();
            nextScreen.setVisible(true);
            nextScreen.setLocationRelativeTo(null);
            
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid credentials.");
        }

        rs.close();
        pstmt.close();
        conn.close();
    } catch (SQLException e) {
        System.out.println("Error: " + e.getMessage());
    }

    }//GEN-LAST:event_logInButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton logInButton;
    private javax.swing.JPasswordField passInput;
    private javax.swing.JLabel passLabel;
    // End of variables declaration//GEN-END:variables
}
