/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rentalbarang;

/**
 *
 * @author ASUS TUF
 */
public class ProfilePannel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ProfilePannel() {
        initComponents();
        
        sessionDataCollect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        nameDisplay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailDisplay = new javax.swing.JLabel();
        dataEditButton = new javax.swing.JButton();
        userHistoryButton = new javax.swing.JButton();
        userListedItemButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JToggleButton();
        phoneDisplay = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        adressDisplay = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        nameDisplay.setText("Name:");

        jLabel2.setText("INI FOTO");

        phoneLabel.setText("Phone:");

        emailDisplay.setText("Email");

        dataEditButton.setText("Edit data");
        dataEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataEditButtonMouseClicked(evt);
            }
        });
        dataEditButton.addActionListener(this::dataEditButtonActionPerformed);

        userHistoryButton.setText("History");

        userListedItemButton.setText("Show your listed item");

        logOutButton.setText("Log out");

        phoneDisplay.setText("Phone Num");

        adressLabel.setText("Adress:");

        adressDisplay.setText("-");
        adressDisplay.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(adressLabel)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailDisplay)))
                            .addComponent(phoneLabel)
                            .addComponent(phoneDisplay)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(adressDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataEditButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userListedItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nameDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adressDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneDisplay)
                .addGap(25, 25, 25)
                .addComponent(dataEditButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userHistoryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userListedItemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOutButton)
                .addGap(0, 127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void sessionDataCollect(){
        nameDisplay.setText(UserSession.getUsername());
        emailDisplay.setText(UserSession.getEmail());
        adressDisplay.setText(UserSession.getAdress());
        phoneDisplay.setText(UserSession.getPhone());
        
    }
    private void dataEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataEditButtonActionPerformed

    private void dataEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataEditButtonMouseClicked
        editDataForm nextScreen = new editDataForm();
            nextScreen.setVisible(true);
            nextScreen.setLocationRelativeTo(null);
            
    }//GEN-LAST:event_dataEditButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adressDisplay;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JButton dataEditButton;
    private javax.swing.JLabel emailDisplay;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton logOutButton;
    private javax.swing.JLabel nameDisplay;
    private javax.swing.JLabel phoneDisplay;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton userHistoryButton;
    private javax.swing.JButton userListedItemButton;
    // End of variables declaration//GEN-END:variables
}
