/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rentalbarang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author ASUS TUF
 */
public class RegisterPannel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPannel
     */
    public RegisterPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameInput = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        passInput = new javax.swing.JPasswordField();
        emailInput = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        phoneInput = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adressInput = new javax.swing.JTextArea();
        registerButton = new javax.swing.JButton();

        nameInput.addActionListener(this::nameInputActionPerformed);

        nameLabel.setText("Name:");

        passLabel.setText("Password:");

        emailInput.addActionListener(this::emailInputActionPerformed);

        emailLabel.setText("Email:");

        phoneLabel.setText("Phone:");

        addressLabel.setText("Adress:");

        adressInput.setColumns(20);
        adressInput.setRows(5);
        jScrollPane1.setViewportView(adressInput);

        registerButton.setText("Register");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameInput)
                    .addComponent(emailInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addressLabel)
                            .addComponent(phoneLabel)
                            .addComponent(passLabel)
                            .addComponent(emailLabel)
                            .addComponent(nameLabel))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
                                                   
    String inputUser = nameInput.getText().trim();
    String inputEmail = emailInput.getText().trim();
    String inputPass = String.valueOf(passInput.getPassword());
    String inputPhone = phoneInput.getText().trim();
    String inputAdress = adressInput.getText();

    // 1. Validation check
    if (inputUser.isEmpty() || inputEmail.isEmpty() || inputPass.isEmpty() || inputPhone.isEmpty() || inputAdress.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }

    Connection conn = DatabaseConnection.connect();
    String sql = "INSERT INTO users (user_name, user_email, user_password, user_phone, user_adress, role) VALUES (?, ?, ?, ?, ?, ?)";

    try {
        // 2. CRUCIAL SYNTAX: Tell the PreparedStatement to return auto-generated keys (the ID)
        PreparedStatement pstmt = conn.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);
        
        pstmt.setString(1, inputUser);
        pstmt.setString(2, inputEmail);
        pstmt.setString(3, inputPass);
        pstmt.setString(4, inputPhone);
        pstmt.setString(5, inputAdress);
        pstmt.setString(6, "user");

        int rowsInserted = pstmt.executeUpdate();

        if (rowsInserted > 0) {
            // 3. Retrieve the auto-generated primary key (id) from MySQL
            java.sql.ResultSet generatedKeys = pstmt.getGeneratedKeys();
            
            if (generatedKeys.next()) {
                int newId = generatedKeys.getInt(1); // Grabs the generated numeric ID
                
                // 4. INSTANT SESSION START: Load the new details into your RAM memory card
                UserSession.startSession(newId, inputUser, inputEmail, inputPass, inputPhone, inputAdress);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Registration Successful! Logging you in...");
                
                // 5. REDIRECT: Open your main form / dashboard instantly
               MainForm nextScreen = new MainForm();
                nextScreen.setVisible(true);
                nextScreen.setLocationRelativeTo(null); 
                
                // Close the current registration window safely
                javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
            }
            generatedKeys.close();
        }

        pstmt.close();
        conn.close();

    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Registration Failed: " + e.getMessage());
    }

    }//GEN-LAST:event_registerButtonMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextArea adressInput;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passInput;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
